server:
  port: 3000
db:
  type: postgres
  port: 5432
  database: auction
  synchronize: false
  username: powerchain
  password: Firstday2010
  host: localhost
jwt:
  expiresIn: 8h
  secret: asdhasdaskhdjaskdh